---
title: "Normality Detection"
author: "Simon Sloan - Alejandro Tirado"
output: html_document
---

## Lets import the dataset
In this case we will use the iris dataset
```{R}
library(MASS)

set.seed(123)

X <- mvrnorm(
  n = 150,
  mu = c(0, 0, 0, 0),
  Sigma = matrix(c(
    1, 0.3, 0.2, 0.1,
    0.3, 1, 0.4, 0.2,
    0.2, 0.4, 1, 0.5,
    0.1, 0.2, 0.5, 1
  ), 4, 4)
)

```

## Describe dataset

In this case, we generate a dataset from a multivariate normal distribution using a predefined mean vector and covariance matrix.

---


## Approximate multivariate normality test (Mardia-based)

---

Here we will start with the application of Doornik–Hansen, according with its respective definition. Of course, here we will use the same structure as Mardia where you can see the first step is stract continuos variables and get Mahalanobis Matrix. 
---

```{r}
    X <- as.matrix(X)
    n <- 150
    p <- 4 
    I <- diag(n)
    Jn <- matrix(1, nrow = n, ncol = n) 
    Xc <- (I - 1/n*Jn)%*%X
    XcT <- t(Xc)
    S <- 1/(n-1) * (XcT%*%Xc)
    # This is the easiest way. However we do it, as before because is better to understand.
    SAuto <- cov(X)

    if (isTRUE(all.equal(S, SAuto))) {
        print("We got the same results")
    }
```

### Now, it is important to get Mahalanobis Matrix
This matrix contains the Mahalanobis structure, where the diagonal elements correspond to squared Mahalanobis distances. 

```{R}
    SInvert = solve(S)
    M = Xc%*%SInvert%*%XcT
```

# First lets compute skewness test
## Get b1p

```{R}
    b1p <- 0

    for (i in 1:nrow(M)) {
        for (j in 1:ncol(M)) {
            
            element <- (1/(n^2)) * (M[i, j])^3
            
            b1p <- b1p + element
            
        }
    }
```

## Lets get EAS and Z1
```{R}
    EAS <- (n/6 * b1p)
    df_skew <- (p*(p+1)*(p+2))/6

    Z1 <- (EAS - df_skew) / sqrt(2*df_skew)
```
The skewness component is approximated using the Mardia skewness statistic.
# Second we compute kurtosis test 
## Get b2p and Z2
As follow it is present the Z2 formula, which represents the value for Z in Mardia Test. Remember, it represents the kurtosis coeficient. Kurtosis is asosciated with how heavy are the tails: 
$$
b_{2,p} =
\frac{1}{n}
\sum_{i=1}^{n}
m_{ii}^{2}
$$

$$
Z_2 =
\frac{b_{2,p} - p(p+2)}
{\sqrt{\frac{8p(p+2)}{n}}}
$$


We will compute this using the formula. 
```{R}
    b2p <- (1/n) * sum(diag(M)^2)
    Z2 <- (b2p - p*(p+2))/sqrt(8*p*(p+2)/n)
```

# Now, lets get DH 
This is the formula for getting the DH stimator statistic and is probability distribution: 
$$
DH = Z_1^2 + Z_2^2
$$
$$
DH \sim \chi^2_2
$$
So lets compute as it indicates: 
```{R}
 DH = Z1^2 + Z2^2
```

# Now lets reject or not $H_0$

In this case our $\alpha$ is going to be 0.10 (different from Mardia Test). 

```{R}
    df <-2 
    alpha<-0.1
    crit <- qchisq(1 - alpha, df)

    x <- seq(0, max(DH, crit)*1.5, length=1000)
    y <- dchisq(x, df)

    plot(x, y, type="l", lwd=2, main="Rejection Region - Doornik-Hansen Test", xlab="DH", ylab="Density")

    x_rej <- seq(crit, max(x), length=500)
    y_rej <- dchisq(x_rej, df)

    polygon(c(crit, x_rej, max(x)), c(0, y_rej, 0), col="red", border=NA)

    abline(v=crit, col="red", lwd=2, lty=2)
    abline(v=DH, col="blue", lwd=2)
```
Since the observed value of the Doornik–Hansen statistic is greater than the critical value, it lies within the rejection region. Therefore, we reject the null hypothesis of multivariate normality.

The rejection obtained in the manual implementation is not due to the data itself, but to the use of approximations that are not properly calibrated. Since the data were generated from a multivariate normal distribution, the correct result should be not to reject normality.

--- 
# Download MVN library

```{R}
install.packages("MVN")   
library(MVN)
```

---
# Convert Dataset into Dataframe 
---
```{R}
X_df <- as.data.frame(X)
```
# Real Doornik–Hansen Test 

--- 

```{R}
result <- mvn(data = X_df, mvn_test = "doornik_hansen")

names(result)

res <- result$multivariate_normality

res[, c("Test", "Statistic", "p.value", "MVN")]
```

The Doornik–Hansen test does not reject the null hypothesis of multivariate normality. This result is consistent with the fact that the dataset was generated from a multivariate normal distribution. The difference with the manual implementation highlights the importance of using properly calibrated statistical tests.

This comparison demonstrates that simplified implementations can lead to misleading conclusions, especially when higher-order moments are not properly standardized.